### PR TITLE
completed task 1 , 2 and Task 3 is 50% completed

### PR DESCRIPTION
**Pull request by HrushikeshBoddu**

### CODE REVIEW

**Comment by lekhaj-soulpage** [comment]
Hi @HrushikeshBoddu  can you share email ID here

**Comment by HrushikeshBoddu** [comment]
Hrushikesh Boddu
***@***.***
+91 9502287088
LinkedIn  | GitHub  | Portfolio
BODDU HRUSHIKESH

**Comment by HrushikeshBoddu** [comment]
Email - bodduhrushikesh@gmail.com
Call - 9502287088

**Comment by HrushikeshBoddu** [comment]
Hrushikesh Boddu
e-mail - ***@***.***
Call - +91 9502287088
BODDU HRUSHIKESH

**Pull request closed without merging**
